name: CI/CD - Blog API with Docker + EC2

on:
  push:
    branches: [ main ]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name:  Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name:  Build JAR with Maven
        run: mvn clean package -DskipTests

      - name:  Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name:  Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-api:latest .

      - name:  Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/blog-api:latest

      - name:  Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/blog-api:latest
            docker stop blog-api || true
            docker rm blog-api || true
            docker run -d --name blog-api -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/blog-api:latest
